export const EXAMPLE = 'EXAMPLE';

export const SET_DIFFICULTY = 'SET_DIFFICULTY'
export const RESET_DIFFICULTY = 'RESET_DIFFICULTY'
export const SET_LEVEL_ID = 'SET_LEVEL_ID'
export const RESET_LEVEL_ID = 'RESET_LEVEL_ID'

export const CREATE_DATABASE = 'CREATE_DATABASE'
export const CLOSE_DATABASE = 'CLOSE_DATABASE'